// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mjpeskjgnhzjfwhdjank.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qcGVza2pnbmh6amZ3aGRqYW5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODU5NjEsImV4cCI6MjA2NTU2MTk2MX0.gynQS0Dnw0LVuEU-2sw6k3DfpVFeJ5KnNXxGsbJnJ3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);